kind: pipeline
name: arm64

platform:
  os: linux
  arch: arm64

steps:
  - name: test
    image: alpine
    commands:
      - apk update
      - apk add file
      - file /bin/busybox
      
  - name: rebuild-cache
    image: meltwater/drone-cache
    pull: always
    settings:
      bucket: drone-cache-bucket
      mount:
        - vendor
      rebuild: true
      region: eu-west-1
      path_style: true
      endpoint: minio:9000
      exit_code: true
    environment:
      AWS_ACCESS_KEY_ID: AKIAIOSFODNN7EXAMPLE
      AWS_SECRET_ACCESS_KEY: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY


trigger:
  branch:
    - master
  event:
    - push
    - pull_request
...
