branches:
  - master

pipeline:
  # restore-cache:
  #     image: meltwater/drone-cache
  #     pull: true
  #     restore: true
  #     bucket: drone-cache-bucket
  #     secrets: [aws_access_key_id, aws_secret_access_key]
  #     region: eu-west-1
  #     mount:
  #       - 'vendor'

  build:
    image: golang:1.11-alpine
    pull: true
    secrets: [aws_access_key_id, aws_secret_access_key]
    commands:
      - env
      - apk add --update make git
      - make drone-cache

  analyze:
    image: golang:1.11-alpine
    pull: true
    environment:
      CGO_ENABLED: '0'
    commands:
      - go vet -v -all -mod=vendor

  test:
    image: golang:1.11-alpine
    pull: true
    environment:
      CGO_ENABLED: '0'
      TEST_ENDPOINT: filestorage:9000
    commands:
      - go test -v -mod=vendor ./... # NOTICE: -race: Needs CGO enabled

  # rebuild-cache:
  #     image: meltwater/drone-cache
  #     pull: true
  #     rebuild: true
  #     bucket: drone-cache-bucket
  #     secrets: [aws_access_key_id, aws_secret_access_key]
  #     region: eu-west-1
  #     mount:
  #       - 'vendor'

  docker-release-latest:
    image: plugins/docker
    pull: true
    repo: meltwater/drone-cache
    tags: latest
    secrets: [docker_username, docker_password]
    when:
      branch: [master]
      event: [push]

  docker-release-tag:
    image: plugins/docker
    repo: meltwater/drone-cache
    tags: '${DRONE_TAG}'
    secrets: [docker_username, docker_password]
    when:
      event: tag
      status: success
      ref: refs/tags/*

  release:
    image: golang:1.11 # golang:1.11-alpine
    secrets: [github_token]
    commands:
      curl -sL https://git.io/goreleaser | bash
    when:
      event: tag
      status: success
      ref: refs/tags/*

  slack:
    group: notifications
    image: plugins/slack
    pull: true
    webhook: https://hooks.slack.com/services/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
    icon_url: https://logo.clearbit.com/drone.io
    username: "Drone: ${DRONE_REPO_NAME}"
    channel: shakespeare-events
    template: |
      :drone-{{build.status}}: *<{{build.link}}|{{uppercasefirst repo.name}} Drone Build {{build.number}}>* completed in {{build.status}}. It took {{since build.started}}
      :github: <https://github.com/{{repo.owner}}/{{repo.name}}/commit/{{build.commit}}|{{repo.owner}}/{{repo.name}}#{{truncate build.commit 8}}>
      > {{build.message}} by <https://github.com/{{build.author}}|{{build.author}}>
    when:
      local: false
      status: [changed, failure] # success

services:
  filestorage:
    image: minio/minio:RELEASE.2018-10-06T00-15-16Z
    environment:
      MINIO_ACCESS_KEY: AKIAIOSFODNN7EXAMPLE
      MINIO_SECRET_KEY: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
      MINIO_REGION: eu-west-1
    ports:
      - 9000:9000
    command: server /data
