branches:
  - master

pipeline:
  clone:
    image: plugins/git
    tags: true

  build:
    image: golang:1.11-alpine
    pull: true
    commands:
      - apk add --update make git
      - make drone-s3-cache

  analyze:
    image: golang:1.11-alpine
    pull: true
    environment:
      CGO_ENABLED: '0'
    commands:
      - go vet -v -all -mod=vendor

  test:
    image: golang:1.11-alpine
    pull: true
    environment:
      CGO_ENABLED: '0'
      TEST_ENDPOINT: filestorage:9000
    commands:
      - go test -race -v -mod=vendor ./...

  docker-release-latest:
    image: plugins/docker
    pull: true
    repo: meltwater/drone-s3-cache
    tags: latest
    secrets: [docker_username, docker_password]
    when:
      branch: [master]
      event: [push]

  docker-release-tag:
    image: plugins/docker
    repo: meltwater/drone-s3-cache
    tags: '${DRONE_TAG}'
    secrets: [docker_username, docker_password]
    when:
      event: tag
      status: success
      ref: refs/tags/*

  release:
    image: golang:1.11 # golang:1.11-alpine
    secrets: [github_token]
    commands:
      curl -sL https://git.io/goreleaser | bash
    when:
      event: tag
      status: success
      ref: refs/tags/*

  slack:
    group: notifications
    image: plugins/slack
    pull: true
    webhook: https://hooks.slack.com/services/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
    icon_url: https://logo.clearbit.com/drone.io
    username: 'Drone'
    channel: haven
    template: |
      :drone-{{build.status}}: *<{{build.link}}|{{uppercasefirst repo.name}} Drone Build {{build.number}}>* completed in {{build.status}}. It took {{since build.started}}
      :github: <https://github.com/{{repo.owner}}/{{repo.name}}/commit/{{build.commit}}|{{repo.owner}}/{{repo.name}}#{{truncate build.commit 8}}>
      > {{build.message}} by <https://github.com/{{build.author}}|{{build.author}}>
    when:
      local: false
      status: [changed, failure]

services:
  filestorage:
    image: minio/minio:RELEASE.2018-10-06T00-15-16Z
    environment:
      MINIO_ACCESS_KEY: AKIAIOSFODNN7EXAMPLE
      MINIO_SECRET_KEY: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
      MINIO_REGION: eu-west-1
    ports:
      - 9000:9000
    command: server /data
