# options for analysis running
run:
  # default concurrency is a available CPU number
  concurrency: 4
  deadline: 1m
  tests: false
  modules-download-mode: vendor
  timeout: 5m

linters:
  enable-all: true
  disable:
    - goerr113
    - errcheck

linters-settings:
  lll:
    line-length: 120
  funlen:
    lines: 70
    statements: 40

