# options for analysis running
run:
  # default concurrency is a available CPU number
  concurrency: 4
  deadline: 1m
  tests: false
  modules-download-mode: vendor

linters:
  enable-all: true
  disable:
    - gochecknoglobals

linters-settings:
  errcheck:
    exclude: .errcheck_excludes
  lll:
    line-length: 120
