before:
  hooks:
    - make clean
    - make fetch-dependencies # go mod vendor
    # OR - go mod download
dist: target/dist
builds:
- env:
  - CGO_ENABLED=0
  goos:
    - darwin
    - linux
    - windows
    - freebsd
  goarch:
    - amd64
    - 386
  ldflags: >
    -s
    -w
    -X main.Version={{.Version}}
    -X main.DateBuilt={{.Date}}
archive:
  format: tar.gz # default. Also available .zip
  replacements:
    darwin: Darwin
    linux: Linux
    386: i386
    amd64: x86_64
  files:
    - README.md
    - CHANGELOG.md
    - LICENSE
checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.txt" # default
snapshot:
  name_template: "SNAPSHOT-{{.ShortCommit}}" # default
changelog:
  sort: asc
  filters:
    exclude:
    - .*
    - typo
    - '^docs:'
    - '^test:'
release:
  github:
    owner: meltwater
    name: drone-cache
  prerelease: auto # in case there is an indicator for this in the tag e.g. v1.0.0-rc1
  disable: false
