#!/bin/sh

# Enable strict mode, see: http://redsymbol.net/articles/unofficial-bash-strict-mode/
set -euo pipefail
IFS=$'\n\t'

echo 'Setting up test environemnt...'
(set -x; docker-compose up -d)
(set -x; mkdir -p ./testcache/cache)

echo 'Testing...'
# make sure https://github.com/rakyll/gotest installed
(set -x; gotest -cover ./...)

echo 'Done.'
exit 0
