FROM golang:1.17.3-alpine3.13 AS builder
RUN apk add --update --no-cache ca-certificates tzdata && update-ca-certificates

FROM scratch as runner

COPY --from=builder /usr/share/zoneinfo /usr/share/zoneinfo
COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/

ADD release/linux/arm64/drone-cache /bin/
ENTRYPOINT ["/bin/drone-cache"]

