# escape=`
FROM mcr.microsoft.com/windows/nanoserver:1909
USER ContainerAdministrator

ENV GODEBUG=netdns=go

ADD release/windows/amd64/drone-cache.exe C:/drone-cache.exe
ENTRYPOINT [ "C:\\drone-cache.exe" ]