FROM golang:1.11-alpine AS builder
RUN apk add --update --no-cache ca-certificates tzdata && update-ca-certificates

RUN echo "[WARNING] Make sure you have run 'goreleaser release', before 'docker build'!"
ADD ./target/dist /opt/

FROM scratch as runner

COPY --from=builder /usr/share/zoneinfo /usr/share/zoneinfo
COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
COPY --from=builder /opt/windows_amd64/drone-cache /bin/drone-cache

ENTRYPOINT ["/bin/drone-cache"]
